### ISSUE TITLE
Reflection Issue

### ISSUE THREAD

**Issue by Fredthedoggy** [Xezard/XGlow#11]
Hi, I'm having a reflection issue using XGlow on a Purpur 1.17.1 Server. Any Ideas?

> `No field with type net.minecraft.EnumChatFormat exists in class PacketPlayOutScoreboardTeam.` Seems to suggest that the packet has been re-worked recently?

```
[23:55:09 WARN]: java.lang.reflect.InvocationTargetException
[23:55:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:55:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[23:55:09 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:55:09 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[23:55:09 WARN]:        at McKingsCore-0.1.jar//me.fredthedoggy.mckingscore.mf.base.CommandHandler.executeCommand(CommandHandler.java:288)
[23:55:09 WARN]:        at McKingsCore-0.1.jar//me.fredthedoggy.mckingscore.mf.base.CommandHandler.execute(CommandHandler.java:203)
[23:55:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[23:55:09 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[23:55:09 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2344)
[23:55:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2155)
[23:55:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2136)
[23:55:09 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:55:09 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:55:09 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[23:55:09 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:55:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:55:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1448)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[23:55:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1426)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1419)
[23:55:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1397)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[23:55:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[23:55:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:55:09 WARN]: Caused by: FieldAccessException: No field with type net.minecraft.EnumChatFormat exists in class PacketPlayOutScoreboardTeam.
[23:55:09 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365)
[23:55:09 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[23:55:09 WARN]:        at XGlow-1.0.5.jar//ru.xezard.glow.packets.WrapperPlayServerScoreboardTeam.setColor(WrapperPlayServerScoreboardTeam.java:118)
[23:55:09 WARN]:        at XGlow-1.0.5.jar//ru.xezard.glow.data.glow.Glow.createTeamPacket(Glow.java:99)
[23:55:09 WARN]:        at XGlow-1.0.5.jar//ru.xezard.glow.data.glow.Glow.processHolder(Glow.java:149)
[23:55:09 WARN]:        at XGlow-1.0.5.jar//ru.xezard.glow.data.glow.Glow.addHolders(Glow.java:121)
[23:55:09 WARN]:        at McKingsCore-0.1.jar//me.fredthedoggy.mckingscore.team.Team.addPlayer(Team.java:40)
[23:55:09 WARN]:        at McKingsCore-0.1.jar//me.fredthedoggy.mckingscore.team.TeamCommand.getTeam(TeamCommand.java:72)
[23:55:09 WARN]:        ... 27 more
```

**Comment by Xezard** [comment]
Since the packet has been changed, the wrapper code will also have to be rewritten for the new version. At the moment, I physically can't get to my computer to do this, and making edits from the phone without checking the plugin is stupid. I will be able to fully update the plugin only after 4 months :(

**Comment by Dymeth** [comment]
> Since the packet has been changed, the wrapper code will also have to be rewritten for the new version. At the moment, I physically can't get to my computer to do this, and making edits from the phone without checking the plugin is stupid. I will be able to fully update the plugin only after 4 months :(

#12 should solve this issue

**Comment by ItWasEnder** [comment]
@Dymeth did this pull actually fix it because I seem to still be getting the error?

**Comment by Dymeth** [comment]
> @Dymeth did this pull actually fix it because I seem to still be getting the error?

Not sure if it fixed, not used XGlow after updating GlowAPI (from SpigotMC).
Could you provide error/exception stack?

**Comment by ItWasEnder** [comment]
> > @Dymeth did this pull actually fix it because I seem to still be getting the error?
> 
> Not sure if it fixed, not used XGlow after updating GlowAPI (from SpigotMC). Could you provide error/exception stack?

I made sure I am on the latest repo code (not just releases) here is the stacktrace

I am using 1.17.1 (paper) and 4.7.0 (ProtocolLib)

https://paste.helpch.at/qebowesuke.rb


--


Nevermind I goofed. I had the old jar on the server :/ The #12 fixed this issue.
