### ISSUE TITLE
Is it possible to support the 1.12.2 version?

### ISSUE THREAD

**Issue by Jeong3954** [Xezard/XGlow#9]
Hello. I'm looking for a Glow API that works with version 1.12.2 as well. I found and used the XGlow, but I get the following error: 

`com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_12_R1.EnumChatFormat exists in class PacketPlayOutScoreboardTeam.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at ru.xezard.glow.packets.WrapperPlayServerScoreboardTeam.setColor(WrapperPlayServerScoreboardTeam.java:118) ~[?:?]
        at ru.xezard.glow.data.glow.Glow.createTeamPacket(Glow.java:99) ~[?:?]
        at ru.xezard.glow.data.glow.Glow.processHolder(Glow.java:149) ~[?:?]
        at ru.xezard.glow.data.glow.Glow.removeHolders(Glow.java:127) ~[?:?]
        at ru.xezard.glow.data.glow.manager.GlowsManager.lambda$removeGlowFrom$1(GlowsManager.java:77) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at ru.xezard.glow.data.glow.manager.GlowsManager.removeGlowFrom(GlowsManager.java:77) ~[?:?]
        at kr.jeong3954.gzone.Main.lambda$onEnable$0(Main.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

Can you support 1.12.2 as well?

**Comment by Xezard** [comment]
I am currently working on the implementation.

**Comment by Xezard** [comment]
Added in https://github.com/Xezard/XGlow/commit/0633a61826b27f3102feb6851d4dca2a73b1a554.
